export const COMMANDS = {
    INIT_DB: "HYREX_COMMAND_INIT_DB",
    RUN_WORKER: "HYREX_COMMAND_RUN_WORKER",
    RUN_WORKER_LISTENER: "HYREX_COMMAND_RUN_WORKER_LISTENER",
    QUEUE_PATTERN: "HYREX_QUEUE_PATTERN",
}
