export const COMMANDS = {
    INIT_DB: "HYREX_COMMAND_INIT_DB",
    RUN_WORKER: "HYREX_COMMAND_RUN_WORKER",
    RUN_ADMIN: "HYREX_COMMAND_RUN_ADMIN",
    RUN_CRON_SCHEDULER: "HYREX_RUN_CRON_SCHEDULER",
    QUEUE_PATTERN: "HYREX_QUEUE_PATTERN",
    EXECUTOR_NAME: "HYREX_EXECUTOR_NAME",
    WORKER_NAME: "HYREX_WORKER_NAME",
}
