import * as fs from 'fs';
import * as path from 'path';
import { promisify } from 'util';
import inquirer from 'inquirer';
import { COLOR_MAP } from '../logging/ColorMap';

const mkdir = promisify(fs.mkdir);
const writeFile = promisify(fs.writeFile);

// Helper function to colorize text
const colorize = (text: string, color: keyof typeof COLOR_MAP): string => {
    const supportsColor = process.stdout.isTTY && process.env.TERM !== 'dumb';
    if (!supportsColor) return text;
    return `\x1b[${COLOR_MAP[color]}m${text}\x1b[${COLOR_MAP.reset}m`;
};

// Template for the hello world app
const generateAppTemplate = (appName: string) => `import { HyrexRegistry } from '@hyrex/hyrex';
import { getHyrexContext } from '@hyrex/hyrex';

export const hy = new HyrexRegistry();

// Define a simple hello world task
const helloWorldTask = hy.task({
    name: 'helloWorld',
    config: {
        queue: 'default',
        timeoutSeconds: 30,
    },
    func: async (input: { name?: string }) => {
        const ctx = getHyrexContext();
        const name = input.name || 'World';
        
        console.log(\`Task ID: \${ctx.taskId}\`);
        console.log(\`Hello, \${name}! Welcome to Hyrex!\`);
        
        // Simulate some work
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        return {
            message: \`Successfully greeted \${name}\`,
            timestamp: new Date().toISOString(),
            taskId: ctx.taskId
        };
    }
});

// Define a cron task that runs every minute
const heartbeatTask = hy.task({
    name: 'heartbeat',
    config: {
        queue: 'monitoring',
        cron: '* * * * *', // Every minute
        timeoutSeconds: 10,
    },
    func: async () => {
        console.log(\`Heartbeat at \${new Date().toISOString()}\`);
        return { status: 'healthy' };
    }
});

// Export tasks for easy access
export { helloWorldTask, heartbeatTask };

// Example usage (uncomment to test):
// if (process.argv.includes('--submit')) {
//     helloWorldTask.send({ name: '${appName}' });
//     console.log('Task submitted!');
// }
`;

const generateHyrexAppTemplate = (appName: string) => `import { HyrexApp } from '@hyrex/hyrex';
import { hy as appRegistry } from './app';

const hyrexApp = new HyrexApp({ 
    name: "${appName}"
});

hyrexApp.addRegistry(appRegistry);
hyrexApp.init();
`;

const generateEnvTemplate = (config: { mode: 'cloud' | 'postgres', apiKey?: string, databaseUrl?: string, s3Bucket?: string }) => {
    const lines: string[] = [];
    
    lines.push('# Hyrex Configuration');
    lines.push('# Generated by hyrex init');
    lines.push('');
    
    if (config.mode === 'cloud') {
        lines.push('# Cloud Mode Configuration');
        lines.push(`HYREX_API_KEY=${config.apiKey || 'your-api-key-here'}`);
    } else {
        lines.push('# PostgreSQL Mode Configuration');
        lines.push(`HYREX_DATABASE_URL=${config.databaseUrl || 'postgresql://user:password@localhost:5432/hyrex'}`);
        
        if (config.s3Bucket) {
            lines.push('');
            lines.push('# S3 Logging Configuration (Optional)');
            lines.push(`HYREX_S3_LOG_BUCKET=${config.s3Bucket}`);
            lines.push('# AWS credentials should be configured via AWS CLI or environment variables');
        }
    }
    
    return lines.join('\n');
};

const generatePackageJsonTemplate = (appName: string) => `{
  "name": "${appName}",
  "version": "1.0.0",
  "description": "A Hyrex application",
  "main": "hyrex-app.ts",
  "scripts": {
    "worker": "hyrex run-worker hyrex-app.ts",
    "worker:multi": "hyrex run-worker hyrex-app.ts 4",
    "init-db": "hyrex init-db hyrex-app.ts",
    "submit": "ts-node app.ts --submit"
  },
  "dependencies": {
    "@hyrex/hyrex": "^0.1.19",
    "dotenv": "^16.5.0"
  },
  "devDependencies": {
    "@types/node": "^22.8.2",
    "ts-node": "^10.9.2",
    "typescript": "^5.7.3"
  }
}
`;

const generateTsConfigTemplate = () => `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "moduleResolution": "node"
  },
  "include": ["./**/*.ts"],
  "exclude": ["node_modules", "dist"]
}
`;

const generateReadmeTemplate = (appName: string, mode: 'cloud' | 'postgres') => `# ${appName}

A Hyrex distributed task execution application.

## Setup

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Configure environment:
   - Copy \`.env.example\` to \`.env\`
   - Update the configuration values

${mode === 'postgres' ? `3. Initialize the database:
   \`\`\`bash
   npm run init-db
   \`\`\`

4. Run workers:` : '3. Run workers:'}
   \`\`\`bash
   npm run worker      # Single worker
   npm run worker:multi # 4 workers
   \`\`\`

${mode === 'postgres' ? '5' : '4'}. Submit a test task:
   \`\`\`bash
   npm run submit
   \`\`\`

## Configuration

- **Mode**: ${mode === 'cloud' ? 'Cloud (using Hyrex platform)' : 'PostgreSQL (self-hosted)'}
${mode === 'cloud' ? '- **API Key**: Set in HYREX_API_KEY environment variable' : '- **Database**: PostgreSQL connection via HYREX_DATABASE_URL'}
${mode === 'postgres' ? '- **Logging**: Optional S3 bucket via HYREX_S3_LOG_BUCKET' : ''}

## Tasks

- **helloWorld**: A simple greeting task that accepts a name parameter
- **heartbeat**: A cron task that runs every minute for monitoring

## Learn More

Visit [https://hyrex.dev](https://hyrex.dev) for documentation and tutorials.
`;

export async function handleInit(appName: string, directory: string) {
    try {
        console.log(colorize('\n🚀 Welcome to Hyrex Init!\n', 'brightCyan'));
        
        // Ask configuration questions using inquirer
        const modeAnswer = await inquirer.prompt([
            {
                type: 'list',
                name: 'mode',
                message: 'Choose your deployment mode:',
                choices: [
                    { name: 'Cloud Mode (using HYREX_API_KEY)', value: 'cloud' },
                    { name: 'PostgreSQL Mode (self-hosted)', value: 'postgres' }
                ]
            }
        ]);
        
        const mode = modeAnswer.mode;
        let apiKey: string | undefined;
        let databaseUrl: string | undefined;
        let s3Bucket: string | undefined;
        
        if (mode === 'cloud') {
            const cloudAnswers = await inquirer.prompt([
                {
                    type: 'input',
                    name: 'apiKey',
                    message: 'Enter your HYREX_API_KEY:',
                    default: 'your-api-key-here'
                }
            ]);
            apiKey = cloudAnswers.apiKey === 'your-api-key-here' ? undefined : cloudAnswers.apiKey;
        } else {
            const pgAnswers = await inquirer.prompt([
                {
                    type: 'input',
                    name: 'databaseUrl',
                    message: 'Enter your PostgreSQL connection string:',
                    default: 'postgresql://localhost:5432/hyrex'
                },
                {
                    type: 'confirm',
                    name: 'useS3',
                    message: 'Do you want to configure S3 logging?',
                    default: false
                }
            ]);
            
            databaseUrl = pgAnswers.databaseUrl;
            
            if (pgAnswers.useS3) {
                const s3Answer = await inquirer.prompt([
                    {
                        type: 'input',
                        name: 's3Bucket',
                        message: 'Enter S3 bucket name:'
                    }
                ]);
                s3Bucket = s3Answer.s3Bucket;
            }
        }
        
        // Create directory structure
        const targetDir = path.resolve(process.cwd(), directory);
        const appDir = directory === '.' ? targetDir : path.join(targetDir, appName);
        
        if (directory !== '.' && !fs.existsSync(appDir)) {
            await mkdir(appDir, { recursive: true });
        }
        
        console.log(colorize(`\n📁 Creating Hyrex app in ${appDir}...\n`, 'brightGreen'));
        
        // Write files
        const files = [
            { name: 'app.ts', content: generateAppTemplate(appName) },
            { name: 'hyrex-app.ts', content: generateHyrexAppTemplate(appName) },
            { name: '.env', content: generateEnvTemplate({ mode, apiKey, databaseUrl, s3Bucket }) },
            { name: '.env.example', content: generateEnvTemplate({ mode }) },
            { name: 'package.json', content: generatePackageJsonTemplate(appName) },
            { name: 'tsconfig.json', content: generateTsConfigTemplate() },
            { name: 'README.md', content: generateReadmeTemplate(appName, mode) },
            { name: '.gitignore', content: 'node_modules/\ndist/\n.env\n*.log\n' }
        ];
        
        for (const file of files) {
            const filePath = path.join(appDir, file.name);
            await writeFile(filePath, file.content);
            console.log(colorize(`  ✓ Created ${file.name}`, 'green'));
        }
        
        console.log(colorize('\n✨ Success! Your Hyrex app is ready.\n', 'brightGreen'));
        console.log('Next steps:');
        
        if (directory !== '.') {
            console.log(`  1. cd ${appName}`);
            console.log('  2. npm install');
        } else {
            console.log('  1. npm install');
        }
        
        if (mode === 'postgres') {
            console.log(`  ${directory !== '.' ? '3' : '2'}. npm run init-db`);
            console.log(`  ${directory !== '.' ? '4' : '3'}. npm run worker`);
        } else {
            console.log(`  ${directory !== '.' ? '3' : '2'}. npm run worker`);
        }
        
        console.log(colorize('\n🎉 Happy coding!\n', 'brightYellow'));
        
    } catch (error) {
        console.error(colorize('\n❌ Error creating Hyrex app:', 'red'), error);
        process.exit(1);
    }
}