import * as fs from 'fs';
import * as path from 'path';
import { promisify } from 'util';
import { COLOR_MAP } from '../logging/ColorMap';

const mkdir = promisify(fs.mkdir);
const writeFile = promisify(fs.writeFile);

// Path to templates directory
const TEMPLATES_DIR = path.join(__dirname, 'templates');

// Helper function to colorize text
const colorize = (text: string, color: keyof typeof COLOR_MAP): string => {
    const supportsColor = process.stdout.isTTY && process.env.TERM !== 'dumb';
    if (!supportsColor) return text;
    return `\x1b[${COLOR_MAP[color]}m${text}\x1b[${COLOR_MAP.reset}m`;
};

// Load template from file and replace placeholders
const loadTemplate = (templateName: string, replacements: Record<string, string> = {}): string => {
    const templatePath = path.join(TEMPLATES_DIR, templateName);
    let content = fs.readFileSync(templatePath, 'utf-8');
    
    // Replace placeholders
    Object.entries(replacements).forEach(([key, value]) => {
        content = content.replace(new RegExp(`{{${key}}}`, 'g'), value);
    });
    
    return content;
};

// Template for the hello world app
const generateAppTemplate = (appName: string) => loadTemplate('tasks.ts.template');

const generateHyrexAppTemplate = (appName: string) => loadTemplate('hyrex-app.ts.template', { APP_NAME: appName });

const generateEnvTemplate = (config: { mode: 'cloud' | 'postgres', apiKey?: string, databaseUrl?: string, s3Bucket?: string }) => {
    const lines: string[] = [];
    
    lines.push('# Hyrex Configuration');
    lines.push('# Generated by hyrex init');
    lines.push('');
    
    if (config.mode === 'cloud') {
        lines.push('# Cloud Mode Configuration');
        lines.push(`HYREX_API_KEY=${config.apiKey || 'your-api-key-here'}`);
    } else {
        lines.push('# PostgreSQL Mode Configuration');
        lines.push(`HYREX_DATABASE_URL=${config.databaseUrl || 'postgresql://user:password@localhost:5432/hyrex'}`);
        
        if (config.s3Bucket) {
            lines.push('');
            lines.push('# S3 Logging Configuration (Optional)');
            lines.push(`HYREX_S3_LOG_BUCKET=${config.s3Bucket}`);
            lines.push('# AWS credentials should be configured via AWS CLI or environment variables');
        }
    }
    
    return lines.join('\n');
};

const generatePackageJsonTemplate = (appName: string) => `{
  "name": "${appName}",
  "version": "1.0.0",
  "description": "A Hyrex application",
  "main": "hyrex-app.ts",
  "scripts": {
    "worker": "hyrex run-worker hyrex-app.ts",
    "worker:multi": "hyrex run-worker hyrex-app.ts 4",
    "init-db": "hyrex init-db hyrex-app.ts",
    "submit": "ts-node tasks.ts --submit"
  },
  "dependencies": {
    "@hyrex/hyrex": "^0.1.19",
    "dotenv": "^16.5.0"
  },
  "devDependencies": {
    "@types/node": "^22.8.2",
    "ts-node": "^10.9.2",
    "typescript": "^5.7.3"
  }
}
`;

const generateTsConfigTemplate = () => `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "moduleResolution": "node"
  },
  "include": ["./**/*.ts"],
  "exclude": ["node_modules", "dist"]
}
`;

const generateHyrexTsConfigTemplate = () => `{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "outDir": "./dist",
    "declaration": true
  }
}
`;


export async function handleInit(appName: string, directory: string) {
    try {
        console.log(colorize('\n🚀 Welcome to Hyrex Init!\n', 'brightCyan'));
        
        // Lazy-load inquirer
        const inquirer = await import('inquirer');
        
        // Ask about app type first
        const appTypeAnswer = await inquirer.default.prompt([
            {
                type: 'list',
                name: 'appType',
                message: 'What would you like to do?',
                choices: [
                    { name: 'Create brand new app (includes all config files)', value: 'new' },
                    { name: 'Install Hyrex in existing app (only core files)', value: 'existing' }
                ]
            }
        ]);
        
        const isNewApp = appTypeAnswer.appType === 'new';
        
        // Ask configuration questions for all installs
        const modeAnswer = await inquirer.default.prompt([
            {
                type: 'list',
                name: 'mode',
                message: 'Choose your deployment mode:',
                choices: [
                    { name: 'Cloud Mode (using HYREX_API_KEY)', value: 'cloud' },
                    { name: 'PostgreSQL Mode (self-hosted)', value: 'postgres' }
                ]
            }
        ]);
        
        const mode = modeAnswer.mode;
        let apiKey: string | undefined;
        let databaseUrl: string | undefined;
        let s3Bucket: string | undefined;
        
        if (mode === 'cloud') {
            const cloudAnswers = await inquirer.default.prompt([
                {
                    type: 'input',
                    name: 'apiKey',
                    message: 'Enter your HYREX_API_KEY:',
                    default: 'your-api-key-here'
                }
            ]);
            apiKey = cloudAnswers.apiKey === 'your-api-key-here' ? undefined : cloudAnswers.apiKey;
        } else {
            const pgAnswers = await inquirer.default.prompt([
                {
                    type: 'input',
                    name: 'databaseUrl',
                    message: 'Enter your PostgreSQL connection string:',
                    default: 'postgresql://localhost:5432/hyrex'
                },
                {
                    type: 'confirm',
                    name: 'useS3',
                    message: 'Do you want to configure S3 logging?',
                    default: false
                }
            ]);
            
            databaseUrl = pgAnswers.databaseUrl;
            
            if (pgAnswers.useS3) {
                const s3Answer = await inquirer.default.prompt([
                    {
                        type: 'input',
                        name: 's3Bucket',
                        message: 'Enter S3 bucket name:'
                    }
                ]);
                s3Bucket = s3Answer.s3Bucket;
            }
        }
        
        // Directory selection with retry loop (after configuration is complete)
        let targetAppName: string;
        let appDir: string;
        
        while (true) {
            // Ask for directory name
            const dirAnswer = await inquirer.default.prompt([
                {
                    type: 'input',
                    name: 'directoryName',
                    message: 'Enter the name for the new directory:',
                    default: 'hyrex',
                    validate: (input) => {
                        if (!input.trim()) {
                            return 'Directory name cannot be empty';
                        }
                        return true;
                    }
                }
            ]);
            
            targetAppName = dirAnswer.directoryName.trim();
            
            // Create directory structure and check for conflicts
            const targetDir = path.resolve(process.cwd(), directory);
            appDir = path.join(targetDir, targetAppName);
            
            // Check if directory already exists and has content
            if (fs.existsSync(appDir)) {
                const dirContents = fs.readdirSync(appDir);
                if (dirContents.length > 0) {
                    console.log(colorize(`\n❌ Directory ${targetAppName} already exists and is not empty.`, 'red'));
                    console.log(colorize('Please choose a different directory name.\n', 'yellow'));
                    continue;
                }
            }
            
            // Check for existing files that would conflict
            const coreFiles = ['tasks.ts', 'hyrex-app.ts', 'tsconfig.hyrex.json'];
            const configFiles = ['.env', '.env.example', 'package.json', 'tsconfig.json', '.gitignore'];
            const files = isNewApp ? [...coreFiles, ...configFiles] : coreFiles;
            
            const existingFiles = [];
            for (const fileName of files) {
                const filePath = path.join(appDir, fileName);
                if (fs.existsSync(filePath)) {
                    existingFiles.push(fileName);
                }
            }
            
            if (existingFiles.length > 0) {
                console.log(colorize(`\n❌ Cannot initialize files in ${targetAppName} because the following files already exist:`, 'red'));
                existingFiles.forEach(name => console.log(colorize(`    ${name}`, 'red')));
                console.log(colorize('\nPlease choose a different directory.\n', 'yellow'));
                continue; // Go back to directory selection
            }
            
            // No conflicts, proceed
            break;
        }
        
        // Create the directory if it doesn't exist
        if (!fs.existsSync(appDir)) {
            await mkdir(appDir, { recursive: true });
        }
        
        console.log(colorize(`\n📁 Creating Hyrex app in ${appDir}...\n`, 'brightGreen'));
        
        // Write files
        const coreFilesToCreate = [
            { name: 'tasks.ts', content: generateAppTemplate(targetAppName) },
            { name: 'hyrex-app.ts', content: generateHyrexAppTemplate(targetAppName) },
            { name: 'tsconfig.hyrex.json', content: generateHyrexTsConfigTemplate() }
        ];
        
        const configFilesToCreate = [
            { name: '.env', content: generateEnvTemplate({ mode, apiKey, databaseUrl, s3Bucket }) },
            { name: '.env.example', content: generateEnvTemplate({ mode }) },
            { name: 'package.json', content: generatePackageJsonTemplate(targetAppName) },
            { name: 'tsconfig.json', content: generateTsConfigTemplate() },
            { name: '.gitignore', content: 'node_modules/\ndist/\n.env\n*.log\n' }
        ];
        
        const files = isNewApp ? [...coreFilesToCreate, ...configFilesToCreate] : coreFilesToCreate;
        
        // Write files (no conflicts at this point)
        for (const file of files) {
            const filePath = path.join(appDir, file.name);
            await writeFile(filePath, file.content);
            console.log(colorize(`  ✓ Created ${file.name}`, 'green'));
        }
        
        console.log(colorize(`\n✨ Success! Your Hyrex ${isNewApp ? 'app' : 'integration'} is ready.\n`, 'brightGreen'));
        console.log('Next steps:');
        
        let stepNumber = 1;
        
        // Add environment variable export step
        if (mode === 'cloud') {
            console.log(`  ${stepNumber}. export HYREX_API_KEY="${apiKey || 'your-api-key-here'}"`);
            stepNumber++;
        } else {
            console.log(`  ${stepNumber}. export HYREX_DATABASE_URL="${databaseUrl || 'postgresql://localhost:5432/hyrex'}"`);
            stepNumber++;
        }
        
        if (mode === 'postgres') {
            console.log(`  ${stepNumber}. npx hyrex init-db ${targetAppName}/hyrex-app.ts`);
            stepNumber++;
        }
        
        console.log(`  ${stepNumber}. npx hyrex run-worker ${targetAppName}/hyrex-app.ts`);
        
        console.log(colorize('\n📚 Documentation: https://hyrex.io/docs', 'brightCyan'));
        console.log(colorize('🎉 Happy coding!\n', 'brightYellow'));
        
    } catch (error) {
        console.error(colorize('\n❌ Error creating Hyrex app:', 'red'), error);
        process.exit(1);
    }
}